### ISSUE TITLE
Get a list of chats

### ISSUE THREAD

**Issue by micw** [JicuNull/WhatsJava#11] opened 2021-05-18 21:14 UTC
Hello,
how can I retrieve a list of all chats?
Kind regards,
Michael.

**Comment by JicuNull** [comment] 2021-05-18 22:15
Hey,
I more or less stopped working on this project some time ago, so this is why there is no method to get a list of all chats by command. However, if you have successfully logged in, then you should get a WebChat array over the onWebChat callback, which is basically a list of chats. Each [WebChat](https://github.com/JicuNull/WhatsJava/blob/master/README.md#objects) object contains information about a direct or group chat. You can find more detailed information in the [README](https://github.com/JicuNull/WhatsJava/blob/master/README.md#message-handlers).

If you no longer have the WebChat array saved, you could simply open a new session.

I hope this helps.

**Comment by micw** [comment] 2021-05-19 05:40
Hi,
thank you. But I already tried this (and expected it after reading some implementations). But after login or session restore, I get "Conn", "Blocklist", "Stream" and "Props". Followed by
```
Logged in successfully! Code: 200
863.--1,
863.--2,
863.--3,
863.--4,
863.--5,
863.--6,
863.--7,
863.--4,{"status":499}
863.--5,{"status":499}
863.--7,{"status":200}
```

No sign of a chat list :-(

**Comment by JicuNull** [comment] 2021-05-19 12:01
I have now tried again with a copy from Github and still can't reproduce your problem.
That's my complete main method:
```java
public static void main(String[] args) {
	WAClient client = new WAClient("credentials.json");
	client.openConnection();
	client.addClientActionListener(new ClientActionListener() {

		@Override
		public void onReceiveLoginResponse(int httpCode) {
			if(httpCode == 200) {
				System.out.println("Logged in successfully! Code: " + httpCode);
			} else {
				System.out.println("Restore of previous session failed! Code: " + httpCode);
			}
		}
			
		@Override
		public void onQRCodeScanRequired(BufferedImage img) {
			System.out.println("Authentication required! Please scan the QR code!");
			saveQRCode(img);
		}

		@Override
		public void onWebChat(WebChat[] chats) {
			for(WebChat webChat : chats) {
				System.out.println(webChat.getName()); // Returns chat name
			}
			System.out.println("You have " + chats.length + " chats");
		}
	});
}
```

Console output without foreach loop:

Logged in successfully! Code: 200
487.--3,
487.--4,
487.--5,
487.--6,
487.--7,
487.--8,
487.--9,
You have 20 chats
487.--6,{"status":499}
487.--7,{"status":499}
487.--9,{"status":200}

**Comment by micw** [comment] 2021-05-19 18:32
I tried that, running 0.1.3-alpha from maven. The  onWebChat method is never called. I got a lot of message and other callbacks.

**Comment by micw** [comment] 2021-05-19 19:31
Seems to be an issue with json->object conversion:

```
["action", null, [["contacts", {"type":"frequent"}, [["message", {"jid":"49xxx@c.us"}, null], ...
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
```

```
["response", {"duplicate":"true","type":"contacts"}, null]
java.lang.IllegalStateException: Not a JSON Array: null
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:107)
```

Still seems not to receive any "chats" events but at least "frequent contacts"

**Comment by JicuNull** [comment] 2021-05-19 19:57
Does it also say in which class and line the error occurs? Can you please give me the entire error?

**Comment by micw** [comment] 2021-05-19 20:59
Oh sorry, missed this. Here it is:
```
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91)
	at icu.jnet.whatsjava.WAMessage.jsonToObject(WAMessage.java:59)
	at icu.jnet.whatsjava.WAClient.onBinaryMessage(WAClient.java:289)
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

It tries to decode the attributes of the null action.

**Comment by JicuNull** [comment] 2021-05-19 22:06
Okay, the exception should be fixed now and you can get the build from JitPack (Version / Commit: 61476f6083)
However, I doubt that this is the problem causing the missing WebChat objects.

**Closed** 2021-07-03 03:55 UTC
